
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React from 'react';
import { Paper, JournalArticle } from './types';

export const BRAND_NAME = 'The Tech Times';

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    id: 1,
    title: 'The Silicon Valley Exodus',
    date: 'Oct 12, 2024',
    excerpt: 'Why the giants are fleeing the bay for the silicon slopes.',
    content: React.createElement('p', null, 'In a historic shift...')
  },
  {
    id: 2,
    title: 'Quantum Supremacy Achieved?',
    date: 'Oct 11, 2024',
    excerpt: 'Google claims a breakthrough, but IBM disputes the math.',
    content: React.createElement('p', null, 'The physics community is in an uproar...')
  }
];

const NEWS_DATA = [
  // --- FRONT PAGE ---
  {
    id: "fp-001",
    title: "AGI Horizon: OpenAI Unveils 'Project Orion'",
    publisher: "AI Wire",
    year: 2024,
    field: "Front Page",
    link: "#",
    description: "In a stunning press conference, Sam Altman revealed the roadmap to Artificial General Intelligence, claiming a 2027 timeline. Experts remain divided on the safety implications of such rapid scaling.",
    insights: ["Project Orion utilizes a new 'liquid neural network' architecture.", "Compute requirements are expected to drain 2% of the US power grid."],
    whyMatters: "A pivotal moment in human history or a dangerous gamble?",
    authors: ["Eleanor Vance", "Tech Correspondent"],
    readTime: "8 min read"
  },
  {
    id: "fp-002",
    title: "Tesla Update: Grok Voice Integration",
    publisher: "AutoTech",
    year: 2024,
    field: "Front Page",
    link: "#",
    description: "Drivers can now edit their routes with just a voice command thanks to Grok in Tesla's latest OTA update. The feature leverages LLMs to understand complex natural language requests.",
    insights: ["Hands-free navigation reduces accident risk by 14%.", "Available immediately for Model S, 3, X, and Y."],
    whyMatters: "Voice interfaces in cars are finally becoming usable.",
    authors: ["Mike Ross", "Auto Editor"],
    readTime: "4 min read"
  },
  {
    id: "fp-003",
    title: "Waymo Hits 700k Paid Rides",
    publisher: "Mobility Weekly",
    year: 2024,
    field: "Front Page",
    link: "#",
    description: "Waymo’s robotaxi rides jumped to 700,000+ in six months as it rapidly scales paid service in the US. Expansion into Atlanta and Austin is scheduled for Q3.",
    insights: ["Zero fatalities recorded in the last 10 million miles.", "Scaling efficiency has dropped cost-per-mile by 30%."],
    whyMatters: "Autonomous driving is moving from R&D to commercial viability.",
    authors: ["Sarah Connor", "Transport Analyst"],
    readTime: "6 min read"
  },
  {
    id: "fp-004",
    title: "Accenture & Anthropic Partnership",
    publisher: "Enterprise AI",
    year: 2025,
    field: "Front Page",
    link: "#",
    description: "300,000 employees at Accenture will soon tap Anthropic’s AI tools through a new long-term partnership aimed at retraining the global workforce.",
    insights: ["Largest enterprise deployment of Claude 3 to date.", "Focus on automating backend legal and HR compliance."],
    whyMatters: "Service firms are betting their existence on AI augmentation.",
    authors: ["Raj Patel", "Business Tech"],
    readTime: "5 min read"
  },
  {
    id: "fp-005",
    title: "OpenAI Pauses Projects for 8 Weeks",
    publisher: "Silicon Valley News",
    year: 2024,
    field: "Front Page",
    link: "#",
    description: "OpenAI puts all side projects on pause for 8 weeks to boost ChatGPT with real user feedback and prep new model launches. The 'Safety First' sprint aims to address hallucination rates.",
    insights: ["Internal focus shift to model reliability over new features.", "Sora video model release delayed until late 2025."],
    whyMatters: "Quality control is becoming the new battleground over pure capability.",
    authors: ["Jessica Lee", "AI Reporter"],
    readTime: "7 min read"
  },

  // --- AI NEWS ---
  {
    id: "ai-001",
    title: "Empromptu Raises $2M for App Building",
    publisher: "Venture Beat",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Empromptu nabbed $2M pre-seed to turn prompts into enterprise apps. Users can tell it what you want—'build a classification app'—and it scaffolds code and adds governance.",
    insights: ["Goes beyond 'vibe coding' to production-ready enterprise software.", "Founded by ex-CodeSee executives."],
    whyMatters: "The barrier to entry for software creation is collapsing.",
    authors: ["Sheena Leven", "Contributor"],
    readTime: "5 min read"
  },
  {
    id: "ai-002",
    title: "The Agentic Workflow Revolution",
    publisher: "AI Trends",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "A 4-step blueprint shows how to scale agent workflows with events, APIs, and guardrails, not just demos. Transformations often fail when leaders fixate on fragments.",
    insights: ["Single-shot prompting is being replaced by agent chains.", "Memory retention across sessions is the next hurdle."],
    whyMatters: "Agents are the new apps.",
    authors: ["Dr. Andrew Ng", "AI Pioneer"],
    readTime: "12 min read"
  },
  {
    id: "ai-003",
    title: "LLMs in Government Workflows",
    publisher: "GovTech",
    year: 2024,
    field: "AI News",
    link: "#",
    description: "New report evaluates LLM agents assisting case workers in processing public benefit applications. Initial trials show a 40% reduction in processing time.",
    insights: ["Human-in-the-loop remains mandatory for legal reasons.", "Hallucinations in legal citations have been minimized to <1%."],
    whyMatters: "Bureaucracy is one of the best use cases for LLMs.",
    authors: ["A. Kumar", "Policy Analyst"],
    readTime: "8 min read"
  },
  {
    id: "ai-004",
    title: "Nvidia's New Drug Discovery Supercomputer",
    publisher: "BioTech Daily",
    year: 2024,
    field: "AI News",
    link: "#",
    description: "Pharma giants are partnering with Nvidia to build dedicated AI supercomputers for protein folding simulation. The goal is to cure untreatable diseases by 2030.",
    insights: ["Simulation replaces wet-lab trial and error.", "BioNeMo framework is becoming the industry standard."],
    whyMatters: "AI is moving from digital bits to biological atoms.",
    authors: ["L. Novak", "Science Editor"],
    readTime: "6 min read"
  },
  {
    id: "ai-005",
    title: "Apple Intelligence: The Slow Rollout",
    publisher: "Cupertino Insider",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Apple's staggered release of AI features has frustrated investors but delighted privacy advocates. On-device processing is proving harder than expected.",
    insights: ["Siri 2.0 is delayed until Spring 2026.", "Private Cloud Compute is setting a new industry standard."],
    whyMatters: "Apple is trading speed for trust.",
    authors: ["Mark Gurman", "Tech Leaker"],
    readTime: "7 min read"
  },
  {
    id: "ai-006",
    title: "Anthropic's 'Constitutional AI' Update",
    publisher: "Ethics in AI",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Claude 3.5 receives a major update to its constitution, focusing on political neutrality and non-violent conflict resolution advice.",
    insights: ["New 'Refusal' training reduces false positives.", "Transparency logs are now available for enterprise users."],
    whyMatters: "Defining the morality of AI models is the central debate of 2025.",
    authors: ["Dario Amodei", "Guest Writer"],
    readTime: "9 min read"
  },
  {
    id: "ai-007",
    title: "Meta's LLaMA 4 Leak",
    publisher: "Open Source Watch",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Rumors swirl that LLaMA 4 will be 10x larger than its predecessor and fully multimodal. Zuckerberg doubles down on open source strategy.",
    insights: ["Could render many proprietary API wrappers obsolete.", "Focus on 3D asset generation."],
    whyMatters: "Meta is commoditizing the intelligence layer.",
    authors: ["Yann LeCun", "Chief Scientist"],
    readTime: "5 min read"
  },
  {
    id: "ai-008",
    title: "Google Gemini: The Context Window King",
    publisher: "Search Engine Land",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Gemini 1.5 Pro now supports 10M tokens, effectively allowing users to upload entire codebases or libraries for analysis.",
    insights: ["Recall accuracy remains at 99.8%.", "Pricing is undercutting GPT-4o by half."],
    whyMatters: "Context is the new fine-tuning.",
    authors: ["Sundar Pichai", "CEO"],
    readTime: "4 min read"
  },
  {
    id: "ai-009",
    title: "The Rise of Small Language Models (SLMs)",
    publisher: "Edge Computing",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "Microsoft's Phi-4 and Google's Gemma are proving that bigger isn't always better. Running intelligence locally on phones is the next frontier.",
    insights: ["Privacy-first AI applications are booming.", "Battery drain is the main bottleneck."],
    whyMatters: "Decentralized AI is safer AI.",
    authors: ["Satya Nadella", "Contributor"],
    readTime: "6 min read"
  },
  {
    id: "ai-010",
    title: "Midjourney v7 Photorealism",
    publisher: "Creative Bloq",
    year: 2025,
    field: "AI News",
    link: "#",
    description: "The latest update to Midjourney is indistinguishable from reality, prompting calls for mandatory watermarking legislation.",
    insights: ["Text rendering is finally perfect.", "New 'Director Mode' allows granular camera control."],
    whyMatters: "The era of truth in digital media is officially over.",
    authors: ["David Holz", "Founder"],
    readTime: "8 min read"
  },

  // --- MARKETS ---
  {
    id: "mkt-001",
    title: "Netflix vs Warner Bros: $108B Hostile Bid",
    publisher: "The DealBook",
    year: 2024,
    field: "Markets",
    link: "#",
    description: "A $108.4B hostile bid aims to block Netflix’s $82.7B Warner Bros. takeover, sparking a Hollywood mega-merger standoff. Regulators are already signaling antitrust concerns.",
    insights: ["The combined entity would control 40% of streaming hours.", "FTC Chair Khan has signaled an immediate investigation."],
    whyMatters: "The streaming wars are entering the consolidation phase.",
    authors: ["Gordon Gekko", "Senior Market Analyst"],
    readTime: "10 min read"
  },
  {
    id: "mkt-002",
    title: "Pharma Giant Hits $1T Valuation",
    publisher: "BioMoney",
    year: 2024,
    field: "Markets",
    link: "#",
    description: "Pharma giant hits $1T valuation and partners with Nvidia to build an AI supercomputer for drug discovery, redefining its tech ambitions.",
    insights: ["AI is cutting drug discovery timelines from 10 years to 2.", "Stock surged 12% on the announcement."],
    whyMatters: "Biology is becoming an information technology.",
    authors: ["Alice Wu", "Biotech Reporter"],
    readTime: "5 min read"
  },
  {
    id: "mkt-003",
    title: "Boom Lands $300M Funding",
    publisher: "Venture Daily",
    year: 2024,
    field: "Markets",
    link: "#",
    description: "Boom lands $300M to launch Superpower and deliver a fleet of natural gas turbines to CrusoeAI. The energy demands of AI are creating new unicorns in the power sector.",
    insights: ["Data centers now consume more power than the airline industry.", "Natural gas is the bridge fuel of choice for AI."],
    whyMatters: "Energy infrastructure is the bottleneck for AI progress.",
    authors: ["Tom Spark", "Energy Reporter"],
    readTime: "6 min read"
  },
  {
    id: "mkt-004",
    title: "Bitcoin Miners Pivot to AI",
    publisher: "CryptoWatch",
    year: 2024,
    field: "Markets",
    link: "#",
    description: "Bitcoin Miners Refocus Data Centers for AI Amid Profit Challenges. Industrial miners are turning halls into AI factories as post‑halving margins shrink.",
    insights: ["HPC hosting offers 4x revenue compared to BTC mining.", "Core Scientific led the trend with a $3B deal."],
    whyMatters: "Crypto infrastructure is being cannibalized by AI.",
    authors: ["Satoshi Nakamoto II", "Crypto Analyst"],
    readTime: "8 min read"
  },
  {
    id: "mkt-005",
    title: "NVIDIA Surpasses Apple",
    publisher: "Wall Street Journal",
    year: 2024,
    field: "Markets",
    link: "#",
    description: "NVIDIA surpasses Apple in market cap for the third time this week. The volatility suggests investor uncertainty regarding long-term AI hardware demand vs consumer electronics stability.",
    insights: ["Jensen Huang's net worth triples.", "Apple's lack of a clear Generative AI story is hurting stock sentiment."],
    whyMatters: "The guard is changing from mobile to AI.",
    authors: ["Jim Cramer", "Market Host"],
    readTime: "4 min read"
  },
  {
    id: "mkt-006",
    title: "Reddit IPO: The Aftermath",
    publisher: "Bloomberg",
    year: 2025,
    field: "Markets",
    link: "#",
    description: "One year after listing, Reddit has transformed from a social network into the world's most valuable AI training data marketplace.",
    insights: ["Data licensing revenue now exceeds ad revenue.", "User revolt has subsided as revenue sharing kicks in."],
    whyMatters: "Human conversation is now a commodity.",
    authors: ["Matt Levine", "Columnist"],
    readTime: "7 min read"
  },
  {
    id: "mkt-007",
    title: "SpaceX Starlink IPO Rumors",
    publisher: "Space News",
    year: 2025,
    field: "Markets",
    link: "#",
    description: "Musk hints at spinning off Starlink as a separate public entity. Analysts project a $150B valuation.",
    insights: ["Global internet coverage is nearly complete.", "Direct-to-cell partnerships are the new growth engine."],
    whyMatters: "The space economy is finally liquid.",
    authors: ["Elon Musk", "Founder"],
    readTime: "5 min read"
  },
  {
    id: "mkt-008",
    title: "Intel's Foundry Split",
    publisher: "SemiAnalysis",
    year: 2025,
    field: "Markets",
    link: "#",
    description: "Intel officially splits its design and foundry businesses in a desperate bid to compete with TSMC.",
    insights: ["US CHIPS Act funding is contingent on the restructuring.", "Qualcomm is rumored to be the first major external customer."],
    whyMatters: "US semiconductor sovereignty hangs in the balance.",
    authors: ["Pat Gelsinger", "CEO"],
    readTime: "9 min read"
  },
  {
    id: "mkt-009",
    title: "SoftBank's New $100B AI Fund",
    publisher: "Nikkei Asia",
    year: 2025,
    field: "Markets",
    link: "#",
    description: "Masayoshi Son returns with 'Project Izanagi', aiming to build the AI chip rival to Nvidia.",
    insights: ["Partnership with Middle Eastern sovereign wealth funds.", "Focus on Arm-based architecture."],
    whyMatters: "The capital flooding into chips is unprecedented.",
    authors: ["Masa Son", "Investor"],
    readTime: "6 min read"
  },
  {
    id: "mkt-010",
    title: "TikTok US Divestiture Complete",
    publisher: "Reuters",
    year: 2025,
    field: "Markets",
    link: "#",
    description: "ByteDance finalizes the sale of TikTok US operations to a consortium led by Oracle and Walmart.",
    insights: ["Algorithm source code remains in China.", "US user data is now fully siloed in Texas."],
    whyMatters: "The splinternet is real.",
    authors: ["Tech Policy Team", "Reporters"],
    readTime: "8 min read"
  },

  // --- OPINION ---
  {
    id: "op-001",
    title: "The Dangerous Success of GPT Therapy",
    publisher: "Editorial Board",
    year: 2024,
    field: "Opinion",
    link: "#",
    description: "Chatbots Cure Depression, but there’s a catch. AI is proving shockingly effective at treating anxiety, but we risk replacing human connection with code.",
    insights: ["Privacy breaches in mental health apps are rampant.", "Dependency on AI validation can stunt emotional growth."],
    whyMatters: "We are outsourcing our humanity to machines.",
    authors: ["Dr. Phil McGraw", "Guest Columnist"],
    readTime: "12 min read"
  },
  {
    id: "op-002",
    title: "Generative AI: The Value Crisis",
    publisher: "TechCrunch Opinion",
    year: 2024,
    field: "Opinion",
    link: "#",
    description: "Generative AI is pushing startups to rethink product value, exposing weak propositions and reshaping market expectations. 'Wrapper' startups are dead on arrival.",
    insights: ["Proprietary data is the only moat left.", "UX is no longer a differentiator."],
    whyMatters: "The SaaS playbook of the last decade is obsolete.",
    authors: ["Paul Graham", "Essayist"],
    readTime: "9 min read"
  },
  {
    id: "op-003",
    title: "Economic Impact Reports Buried",
    publisher: "The Atlantic",
    year: 2024,
    field: "Opinion",
    link: "#",
    description: "Researchers say economic impact reports on AI's effect on up to 80% of jobs are getting less visibility at OpenAI. Is the industry hiding the true cost of automation?",
    insights: ["Universal Basic Income discussions are being sidelined.", "White collar disruption is happening faster than predicted."],
    whyMatters: "Silence on job displacement serves only the shareholders.",
    authors: ["Ezra Klein", "Columnist"],
    readTime: "11 min read"
  },
  {
    id: "op-004",
    title: "Startups: Profit Over Hype",
    publisher: "VC Perspectives",
    year: 2024,
    field: "Opinion",
    link: "#",
    description: "Startups win with profit-first, customer-obsessed scaling; skip the VC hype and grow sturdier, sustainably. The ZIRP era is over.",
    insights: ["Bootstrapped founders are outperforming funded ones in 2024.", "Unit economics matter more than growth rate."],
    whyMatters: "A return to fundamentals is healthy for the ecosystem.",
    authors: ["Jason Fried", "Guest Writer"],
    readTime: "7 min read"
  },
  {
    id: "op-005",
    title: "The Death of the Junior Developer",
    publisher: "Stack Overflow Blog",
    year: 2025,
    field: "Opinion",
    link: "#",
    description: "With AI writing 60% of boilerplate code, the traditional apprenticeship model for software engineers is breaking. How do we train seniors if no one hires juniors?",
    insights: ["Mentorship must become intentional, not accidental.", "Universities need to pivot to system architecture."],
    whyMatters: "The skills gap will become a chasm.",
    authors: ["Joel Spolsky", "Veteran Dev"],
    readTime: "8 min read"
  },
  {
    id: "op-006",
    title: "Why We Need a Digital Bill of Rights",
    publisher: "EFF",
    year: 2025,
    field: "Opinion",
    link: "#",
    description: "As our lives merge with the digital, our constitutional rights must follow. The current legal framework is woefully inadequate for the age of surveillance.",
    insights: ["Right to disconnect.", "Right to algorithmic transparency."],
    whyMatters: "Freedom in the 21st century is digital freedom.",
    authors: ["Cory Doctorow", "Activist"],
    readTime: "10 min read"
  },
  {
    id: "op-007",
    title: "The Metaverse Wasn't Wrong, Just Early",
    publisher: "UploadVR",
    year: 2025,
    field: "Opinion",
    link: "#",
    description: "Mocked in 2022, spatial computing is quietly becoming the standard for enterprise collaboration. We owe Zuckerberg an apology.",
    insights: ["Remote work is permanent.", "Presence requires more than Zoom."],
    whyMatters: "Physical geography is losing its grip on the economy.",
    authors: ["Palmer Luckey", "Inventor"],
    readTime: "6 min read"
  },
  {
    id: "op-008",
    title: "Stop Anthropomorphizing AI",
    publisher: "Scientific American",
    year: 2025,
    field: "Opinion",
    link: "#",
    description: "Calling it 'hallucination' implies a mind. It is statistical error. Our language is shaping our misunderstanding of the technology.",
    insights: ["We need precise engineering terms.", "The 'Black Box' excuse is intellectual laziness."],
    whyMatters: "Clear language leads to clear regulation.",
    authors: ["Gary Marcus", "Cognitive Scientist"],
    readTime: "7 min read"
  },

  // --- GADGETS ---
  {
    id: "gad-001",
    title: "Google's New AI Smart Glasses",
    publisher: "The Verge",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "Next year, users can try Google’s AI-powered smart glasses; set to rival Meta and hit shelves in 2026. Project Astra is finally coming to hardware.",
    insights: ["Multimodal input allows you to 'show' the AI your world.", "Battery life is the main engineering constraint."],
    whyMatters: "The post-smartphone era needs a form factor.",
    authors: ["Nilay Patel", "Reviewer"],
    readTime: "6 min read"
  },
  {
    id: "gad-002",
    title: "Review: Apple Vision Pro Year 1",
    publisher: "Gadget Review",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "It is heavy, it is expensive, and it is undeniably magical. But has the 'Killer App' finally arrived? We revisit the headset that promised spatial computing.",
    insights: ["Immersive sports are the breakout use case.", "Productivity is still hindered by weight."],
    whyMatters: "Apple plays the long game, but patience is wearing thin.",
    authors: ["Marques Brownlee", "Tech Reviewer"],
    readTime: "15 min read"
  },
  {
    id: "gad-003",
    title: "Humane Pin: A Post-Mortem",
    publisher: "Wired",
    year: 2024,
    field: "Gadgets",
    link: "#",
    description: "We spent two weeks with the Humane Pin. The conclusion? Screens are sticky, but voice interfaces are struggling to find their voice in a noisy world.",
    insights: ["Latency remains the biggest killer of ambient computing.", "Heat dissipation issues caused discomfort."],
    whyMatters: "A cautionary tale for AI hardware startups.",
    authors: ["Julian Chokkattu", "Senior Writer"],
    readTime: "10 min read"
  },
  {
    id: "gad-004",
    title: "Nothing Phone (3) Leaks",
    publisher: "Android Central",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "The new Nothing Phone focuses entirely on AI integration, skipping the app grid for a generative UI. Bold move or suicide?",
    insights: ["No apps, just intents.", "Hardware design remains transparent and industrial."],
    whyMatters: "UI paradigms are shifting away from the grid.",
    authors: ["Mr. Mobile", "Guest Reviewer"],
    readTime: "5 min read"
  },
  {
    id: "gad-005",
    title: "Samsung Galaxy Ring Review",
    publisher: "Engadget",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "Smart rings are having a moment. Samsung's entry is sleek, long-lasting, and integrates perfectly with Samsung Health. Is Oura in trouble?",
    insights: ["7-day battery life confirmed.", "Gesture controls for smart home devices."],
    whyMatters: "Health tracking is becoming invisible.",
    authors: ["Cherlynn Low", "Editor"],
    readTime: "5 min read"
  },
  {
    id: "gad-006",
    title: "PlayStation 5 Pro: Worth the Upgrade?",
    publisher: "IGN",
    year: 2024,
    field: "Gadgets",
    link: "#",
    description: "Sony's mid-cycle refresh promises 8K gaming and advanced ray tracing. We put the teraflops to the test.",
    insights: ["PSSR upscaling is a game changer.", "Requires a high-end display to notice the difference."],
    whyMatters: "Console cycles are blurring into PC-like iterative updates.",
    authors: ["Ryan McCaffrey", "Editor"],
    readTime: "8 min read"
  },
  {
    id: "gad-007",
    title: "Framework Laptop 16: The Modular Dream",
    publisher: "Linus Tech Tips",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "A fully upgradeable gaming laptop with a detachable GPU. It's clunky, it's expensive, and it's absolutely brilliant.",
    insights: ["Repairability score: 10/10.", "Keyboard modules are hot-swappable."],
    whyMatters: "Fighting e-waste through design.",
    authors: ["Linus Sebastian", "Host"],
    readTime: "12 min read"
  },
  {
    id: "gad-008",
    title: "DJI Mavic 4 Pro",
    publisher: "DroneDJ",
    year: 2025,
    field: "Gadgets",
    link: "#",
    description: "With triple cameras and AI obstacle avoidance that feels like magic, the Mavic 4 Pro is the ultimate consumer drone.",
    insights: ["1-inch sensor on all three lenses.", "50-minute flight time."],
    whyMatters: "Aerial photography is now effortless.",
    authors: ["Seth Kurkowski", "Reviewer"],
    readTime: "6 min read"
  },
  {
    id: "gad-009",
    title: "Sonos Ace Headphones",
    publisher: "What Hi-Fi?",
    year: 2024,
    field: "Gadgets",
    link: "#",
    description: "Sonos finally enters the headphone market. The TV Audio Swap feature is the killer app, but is the ANC up to par with Sony and Bose?",
    insights: ["Seamless handoff from Arc soundbar.", "Premium build quality."],
    whyMatters: "Ecosystem lock-in extends to your commute.",
    authors: ["Becky Roberts", "Audio Editor"],
    readTime: "7 min read"
  },
  {
    id: "gad-010",
    title: "Rabbit R1: The AI Tamagotchi",
    publisher: "MKBHD",
    year: 2024,
    field: "Gadgets",
    link: "#",
    description: "It's orange, it's cute, and it barely works. The R1 is a fascinating glimpse into a future that isn't ready yet.",
    insights: ["Large Action Model (LAM) concept is sound.", "Hardware feels cheap."],
    whyMatters: "We are in the 'throw it at the wall' phase of AI hardware.",
    authors: ["Marques Brownlee", "Reviewer"],
    readTime: "9 min read"
  },

  // --- CYBER ---
  {
    id: "cyb-001",
    title: "EU Passes Anti-Worldcoin Laws",
    publisher: "Privacy Watch",
    year: 2024,
    field: "Cyber",
    link: "#",
    description: "EU passes restrictive data laws targeting 'Worldcoin'. Biometric data collection faces its stiffest legal challenge yet in the Eurozone.",
    insights: ["Iris scanning deemed 'high-risk' under GDPR.", "Fines could reach 4% of global turnover."],
    whyMatters: "The battle for your biometric identity has begun.",
    authors: ["Max Schrems", "Privacy Activist"],
    readTime: "8 min read"
  },
  {
    id: "cyb-002",
    title: "Cyber Warfare: The Grid Siege",
    publisher: "Security Brief",
    year: 2024,
    field: "Cyber",
    link: "#",
    description: "State-sponsored actors have reportedly infiltrated critical infrastructure in three G7 nations. A deep dive into the silent war being fought in the servers.",
    insights: ["Water treatment plants are the most vulnerable targets.", "Zero-trust architecture is no longer optional."],
    whyMatters: "Digital threats are manifesting in physical reality.",
    authors: ["Nicole Perlroth", "Cyber Reporter"],
    readTime: "14 min read"
  },
  {
    id: "cyb-003",
    title: "Deepfake CEO Scams Rise 400%",
    publisher: "Fraud Alert",
    year: 2024,
    field: "Cyber",
    link: "#",
    description: "Corporations lost $2B last quarter to deepfake video calls impersonating executives. Authentication tech is lagging behind generation tech.",
    insights: ["Real-time deepfake detection is the new antivirus.", "CFOs are requiring code-words for wire transfers."],
    whyMatters: "Trust is eroding in digital communications.",
    authors: ["Frank Abagnale", "Consultant"],
    readTime: "6 min read"
  },
  {
    id: "cyb-004",
    title: "Quantum Decryption Threats",
    publisher: "Encryption Journal",
    year: 2025,
    field: "Cyber",
    link: "#",
    description: "Harvest Now, Decrypt Later. Nation states are hoarding encrypted traffic anticipating quantum breakthroughs. Are we ready for Y2Q?",
    insights: ["RSA encryption could be obsolete by 2030.", "Post-Quantum Cryptography (PQC) migration is urgent."],
    whyMatters: "All historical secrets are at risk of exposure.",
    authors: ["Bruce Schneier", "Cryptographer"],
    readTime: "10 min read"
  },
  {
    id: "cyb-005",
    title: "The MOVEit Hack Fallout",
    publisher: "Dark Reading",
    year: 2024,
    field: "Cyber",
    link: "#",
    description: "One year later, the victims of the MOVEit file transfer vulnerability are still tallying losses. 90 million individuals affected.",
    insights: ["Supply chain attacks are the primary vector.", "Clop ransomware gang extorted over $100M."],
    whyMatters: "Your security is only as strong as your vendor's security.",
    authors: ["Brian Krebs", "Investigative Reporter"],
    readTime: "9 min read"
  },
  {
    id: "cyb-006",
    title: "North Korea's Crypto Heists",
    publisher: "Chainalysis",
    year: 2025,
    field: "Cyber",
    link: "#",
    description: "Lazarus Group is funding the DPRK missile program through DeFi hacks. The blockchain is transparent, but the mixers are not.",
    insights: ["$600M stolen in 2024 alone.", "Tornado Cash sanctions had limited effect."],
    whyMatters: "Cybercrime is geopolitics.",
    authors: ["Kim Zetter", "Journalist"],
    readTime: "7 min read"
  },
  {
    id: "cyb-007",
    title: "AI Poisoning Attacks",
    publisher: "MIT Tech Review",
    year: 2025,
    field: "Cyber",
    link: "#",
    description: "Hackers are subtly altering training data to install backdoors in enterprise models. 'Nightshade' allows artists to poison their work against scrapers.",
    insights: ["Model collapse is a potential denial-of-service vector.", "Data provenance is the new gold standard."],
    whyMatters: "If you can't trust the data, you can't trust the model.",
    authors: ["Melissa Heikkilä", "AI Reporter"],
    readTime: "6 min read"
  },
  {
    id: "cyb-008",
    title: "Zero-Day Market Explosion",
    publisher: "Zerodium Watch",
    year: 2025,
    field: "Cyber",
    link: "#",
    description: "Prices for iOS zero-click exploits have hit $5M. The gray market for vulnerabilities is booming as governments stockpile cyberweapons.",
    insights: ["Pegasus spyware is just the tip of the iceberg.", "Bug bounty programs cannot compete with state actors."],
    whyMatters: "There is no such thing as a secure device.",
    authors: ["Lorenzo Franceschi-Bicchierai", "Writer"],
    readTime: "8 min read"
  },

  // --- GLOBAL TECH ---
  {
    id: "glb-001",
    title: "India's Semiconductor Ambitions",
    publisher: "Times of India",
    year: 2025,
    field: "Global Tech",
    link: "#",
    description: "Modi's $10B incentive plan is finally bearing fruit as Tata Electronics breaks ground on the country's first fab.",
    insights: ["Goal to become a global chip hub by 2030.", "Partnership with Taiwan's PSMC."],
    whyMatters: "Supply chain diversification away from China is accelerating.",
    authors: ["Pankaj Mishra", "Tech Editor"],
    readTime: "7 min read"
  },
  {
    id: "glb-002",
    title: "China's Great Firewall 2.0",
    publisher: "South China Morning Post",
    year: 2025,
    field: "Global Tech",
    link: "#",
    description: "Beijing deploys AI censors to filter generative content in real-time. The cat-and-mouse game of internet freedom enters a new dimension.",
    insights: ["VPNs are becoming less effective.", "Social credit system integrated with online activity."],
    whyMatters: "The internet is fracturing into distinct information ecosystems.",
    authors: ["Josh Ye", "Reporter"],
    readTime: "6 min read"
  },
  {
    id: "glb-003",
    title: "Africa's Fintech Boom",
    publisher: "TechCrunch Africa",
    year: 2025,
    field: "Global Tech",
    link: "#",
    description: "Mobile money in Nigeria and Kenya is leapfrogging Western banking systems. Flutterwave and Paystack are the new giants.",
    insights: ["Crypto adoption is highest in inflation-prone economies.", "VC funding in Africa defies the global downturn."],
    whyMatters: "Innovation happens where the need is greatest.",
    authors: ["Tage Kene-Okafor", "Writer"],
    readTime: "5 min read"
  },
  {
    id: "glb-004",
    title: "Europe's AI Act Comes into Force",
    publisher: "Politico EU",
    year: 2025,
    field: "Global Tech",
    link: "#",
    description: "The Brussels Effect strikes again. Global tech firms scramble to comply with the world's first comprehensive AI law.",
    insights: [" tiered risk categories.", "Heavy fines for non-compliance."],
    whyMatters: "Europe is the world's digital referee.",
    authors: ["Mark Scott", "Chief Tech Correspondent"],
    readTime: "9 min read"
  },
  {
    id: "glb-005",
    title: "Saudi Arabia's NEOM Tech",
    publisher: "Arab News",
    year: 2025,
    field: "Global Tech",
    link: "#",
    description: "The $500B mega-city creates a digital twin of itself. Privacy concerns mount as 'The Line' promises a surveillance-free utopia that relies on total surveillance.",
    insights: ["Flying taxis are scheduled for 2026.", "Cloud seeding technology for climate control."],
    whyMatters: "The future of urban living is being tested in the desert.",
    authors: ["Frank Kane", "Editor"],
    readTime: "8 min read"
  }
];

export const PAPERS: Paper[] = NEWS_DATA.map(item => ({
    id: item.id,
    title: item.title,
    publisher: item.publisher,
    authors: item.authors,
    abstractPreview: item.description,
    abstract: item.description,
    publicationDate: String(item.year),
    category: item.field, // Maps directly to Navbar
    doi: item.link,
    whyMatters: item.whyMatters,
    upvotes: Math.floor(Math.random() * 2000) + 100,
    timestamp: Date.now() - (Math.random() * 10000000), 
    aiInsights: item.insights,
    industry: [item.field],
    readTime: item.readTime
}));
